webtalk_init -webtalk_dir C:\\Users\\Alexander\\Documents\\GitHub\\Thesis\\Vivado\\TrapezSW\\TrapezSW.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "fr sep. 18 14:50:28 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5k5in71tmc4vrooebktbhkqslu" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1442573433488" -context "sdk\\\\application/1442573433488"
webtalk_add_data -client sdk -key hwid -value "1442409514270" -context "sdk\\\\application/1442573433488"
webtalk_add_data -client sdk -key bspid -value "1442472044798" -context "sdk\\\\application/1442573433488"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1442573433488"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1442573433488"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1442573433488"
webtalk_add_data -client sdk -key uid -value "1442573897946" -context "sdk\\\\application/1442573897946"
webtalk_add_data -client sdk -key hwid -value "1442409514270" -context "sdk\\\\application/1442573897946"
webtalk_add_data -client sdk -key bspid -value "1442472044798" -context "sdk\\\\application/1442573897946"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1442573897946"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1442573897946"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1442573897946"
webtalk_add_data -client sdk -key uid -value "1442574106521" -context "sdk\\\\application/1442574106521"
webtalk_add_data -client sdk -key hwid -value "1442409514270" -context "sdk\\\\application/1442574106521"
webtalk_add_data -client sdk -key bspid -value "1442472044798" -context "sdk\\\\application/1442574106521"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1442574106521"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1442574106521"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1442574106521"
webtalk_transmit -clientid 2007107140 -regid "" -xml C:\\Users\\Alexander\\Documents\\GitHub\\Thesis\\Vivado\\TrapezSW\\TrapezSW.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Alexander\\Documents\\GitHub\\Thesis\\Vivado\\TrapezSW\\TrapezSW.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Alexander\\Documents\\GitHub\\Thesis\\Vivado\\TrapezSW\\TrapezSW.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
